# -*- coding: utf-8 -*-
"""deep_learning_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJcRFZHKkOT3iqHGRe4Z1B28Pv8zIn5Z
"""

from sklearn.manifold import TSNE
from sklearn.datasets import load_iris
from numpy import reshape
import seaborn as sns
import pandas as pd

iris=load_iris()
x=iris.data
y=iris.target

tsne= TSNE(n_components=2, verbose=1, random_state=123)
z=tsne.fit_transform(x)

df=pd.DataFrame()
df["y"]=y
df["comp_1"]=z[:,0]
df["comp_2"]=z[:,1]

sns.scatterplot(x="comp_1", y="comp_2", hue=df.y.tolist(), palette=sns.color_palette("hls",3), data=df).set(title="iris data T-SNE projection")